version: '3.6'

services:
  web:
    environment:
      - ENVIRONMENT=development
    build:
      dockerfile: docker/Dockerfile.development
      context: .
    command: lein ring server-headless 8000
    volumes:
      - .:/usr/src/codcheck-api
      - ~/.m2:/root/.m2
    ports:
      - "8000:8000"

networks:
  default:
    external:
      name: codcheck-network
