FROM openjdk:8-alpine3.8
MAINTAINER Karol Wojcik <kwcharllie379@gmail.com>

ENV HOST 0.0.0.0
ENV ENVIRONMENT=development

WORKDIR /usr/src/codcheck-api
COPY codcheck-api.jar codcheck-api.jar

EXPOSE 8000

ENTRYPOINT ["java", "-jar","codcheck-api.jar"]
